shop:
  image: secupay/docker-shop-shopware5
  # build: /home/decemvre/docker/secuDocker/docker-shop-shopware5

manager:
  extends:
    file: ../common.yml
    service: manager
  links:
    - database
  volumes_from:
    - shop

web:
  extends:
    file: ../common.yml
    service: nginx
  links:
    - phpfpm
  volumes_from:
    - manager

phpfpm:
  extends:
    file: ../common.yml
    service: phpfpm
  links:
    - database
  volumes_from:
    - manager

database:
  extends:
    file: ../common.yml
    service: mysql
