##############################
# Apache
##############################

# Base image
##############################
FROM httpd:latest

# Maintainer
##############################
MAINTAINER decemvre decemvre@gmail.com

# Files
##############################

# Config
##############################

# Ports
##############################
EXPOSE 80